// Copyright 2021-2022, University of Colorado Boulder

/**
 * Auto-generated from modulify, DO NOT manually modify.
 */
/* eslint-disable */
import getStringModule from '../../chipper/js/getStringModule.js';
import LinkableProperty from '../../axon/js/LinkableProperty.js';
import fluidPressureAndFlow from './fluidPressureAndFlow.js';

type StringsType = {
  'fluid-pressure-and-flow': {
    'title': string;
    'titleStringProperty': LinkableProperty<string>;
  };
  'waterTowerScreenTitle': string;
  'waterTowerScreenTitleStringProperty': LinkableProperty<string>;
  'earth': string;
  'earthStringProperty': LinkableProperty<string>;
  'fluxUnitsMetric': string;
  'fluxUnitsMetricStringProperty': LinkableProperty<string>;
  'fluidDensity': string;
  'fluidDensityStringProperty': LinkableProperty<string>;
  'pressure': string;
  'pressureStringProperty': LinkableProperty<string>;
  'honey': string;
  'honeyStringProperty': LinkableProperty<string>;
  'dots': string;
  'dotsStringProperty': LinkableProperty<string>;
  'mPerSPerS': string;
  'mPerSPerSStringProperty': LinkableProperty<string>;
  'densityUnitsEnglish': string;
  'densityUnitsEnglishStringProperty': LinkableProperty<string>;
  'ruler': string;
  'rulerStringProperty': LinkableProperty<string>;
  'mPerS': string;
  'mPerSStringProperty': LinkableProperty<string>;
  'hose': string;
  'hoseStringProperty': LinkableProperty<string>;
  'matchLeakage': string;
  'matchLeakageStringProperty': LinkableProperty<string>;
  'atmospheres': string;
  'atmospheresStringProperty': LinkableProperty<string>;
  'slowMotion': string;
  'slowMotionStringProperty': LinkableProperty<string>;
  'ftPerSPerS': string;
  'ftPerSPerSStringProperty': LinkableProperty<string>;
  'measuringTape': string;
  'measuringTapeStringProperty': LinkableProperty<string>;
  'fill': string;
  'fillStringProperty': LinkableProperty<string>;
  'psi': string;
  'psiStringProperty': LinkableProperty<string>;
  'english': string;
  'englishStringProperty': LinkableProperty<string>;
  'friction': string;
  'frictionStringProperty': LinkableProperty<string>;
  'rateUnitsMetric': string;
  'rateUnitsMetricStringProperty': LinkableProperty<string>;
  'flowRate': string;
  'flowRateStringProperty': LinkableProperty<string>;
  'flowRateWithColon': string;
  'flowRateWithColonStringProperty': LinkableProperty<string>;
  'kPa': string;
  'kPaStringProperty': LinkableProperty<string>;
  'ft': string;
  'ftStringProperty': LinkableProperty<string>;
  'gasoline': string;
  'gasolineStringProperty': LinkableProperty<string>;
  'manual': string;
  'manualStringProperty': LinkableProperty<string>;
  'on': string;
  'onStringProperty': LinkableProperty<string>;
  'area': string;
  'areaStringProperty': LinkableProperty<string>;
  'rateUnitsEnglish': string;
  'rateUnitsEnglishStringProperty': LinkableProperty<string>;
  'water': string;
  'waterStringProperty': LinkableProperty<string>;
  'readoutFeet': string;
  'readoutFeetStringProperty': LinkableProperty<string>;
  'gravity': string;
  'gravityStringProperty': LinkableProperty<string>;
  'metric': string;
  'metricStringProperty': LinkableProperty<string>;
  'massLabelPattern': string;
  'massLabelPatternStringProperty': LinkableProperty<string>;
  'atm': string;
  'atmStringProperty': LinkableProperty<string>;
  'grid': string;
  'gridStringProperty': LinkableProperty<string>;
  'normal': string;
  'normalStringProperty': LinkableProperty<string>;
  'readoutMeters': string;
  'readoutMetersStringProperty': LinkableProperty<string>;
  'off': string;
  'offStringProperty': LinkableProperty<string>;
  'atmosphere': string;
  'atmosphereStringProperty': LinkableProperty<string>;
  'areaUnitsMetric': string;
  'areaUnitsMetricStringProperty': LinkableProperty<string>;
  'densityUnitsMetric': string;
  'densityUnitsMetricStringProperty': LinkableProperty<string>;
  'valueWithUnitsPattern': string;
  'valueWithUnitsPatternStringProperty': LinkableProperty<string>;
  'm': string;
  'mStringProperty': LinkableProperty<string>;
  'fluxUnitsEnglish': string;
  'fluxUnitsEnglishStringProperty': LinkableProperty<string>;
  'units': string;
  'unitsStringProperty': LinkableProperty<string>;
  'flux': string;
  'fluxStringProperty': LinkableProperty<string>;
  'fluxMeter': string;
  'fluxMeterStringProperty': LinkableProperty<string>;
  'ftPerS': string;
  'ftPerSStringProperty': LinkableProperty<string>;
  'areaUnitsEnglish': string;
  'areaUnitsEnglishStringProperty': LinkableProperty<string>;
  'mars': string;
  'marsStringProperty': LinkableProperty<string>;
  'jupiter': string;
  'jupiterStringProperty': LinkableProperty<string>;
  'mysteryFluid': string;
  'mysteryFluidStringProperty': LinkableProperty<string>;
  'mysteryPlanet': string;
  'mysteryPlanetStringProperty': LinkableProperty<string>;
  'planetA': string;
  'planetAStringProperty': LinkableProperty<string>;
  'planetB': string;
  'planetBStringProperty': LinkableProperty<string>;
  'planetC': string;
  'planetCStringProperty': LinkableProperty<string>;
  'fluidA': string;
  'fluidAStringProperty': LinkableProperty<string>;
  'fluidB': string;
  'fluidBStringProperty': LinkableProperty<string>;
  'fluidC': string;
  'fluidCStringProperty': LinkableProperty<string>;
  'feet': string;
  'feetStringProperty': LinkableProperty<string>;
  'meters': string;
  'metersStringProperty': LinkableProperty<string>;
  'speed': string;
  'speedStringProperty': LinkableProperty<string>;
  'flowScreenTitle': string;
  'flowScreenTitleStringProperty': LinkableProperty<string>;
  'underPressureScreenTitle': string;
  'underPressureScreenTitleStringProperty': LinkableProperty<string>;
};

const FluidPressureAndFlowStrings = getStringModule( 'FLUID_PRESSURE_AND_FLOW' ) as StringsType;

fluidPressureAndFlow.register( 'FluidPressureAndFlowStrings', FluidPressureAndFlowStrings );

export default FluidPressureAndFlowStrings;
