// Copyright 2021-2022, University of Colorado Boulder

/**
 * Auto-generated from modulify, DO NOT manually modify.
 */
/* eslint-disable */
import getStringModule from '../../chipper/js/getStringModule.js';
import TReadOnlyProperty from '../../axon/js/TReadOnlyProperty.js';
import fluidPressureAndFlow from './fluidPressureAndFlow.js';

type StringsType = {
  'fluid-pressure-and-flow': {
    'title': string;
    'titleStringProperty': TReadOnlyProperty<string>;
  };
  'waterTowerScreenTitle': string;
  'waterTowerScreenTitleStringProperty': TReadOnlyProperty<string>;
  'earth': string;
  'earthStringProperty': TReadOnlyProperty<string>;
  'fluxUnitsMetric': string;
  'fluxUnitsMetricStringProperty': TReadOnlyProperty<string>;
  'fluidDensity': string;
  'fluidDensityStringProperty': TReadOnlyProperty<string>;
  'pressure': string;
  'pressureStringProperty': TReadOnlyProperty<string>;
  'honey': string;
  'honeyStringProperty': TReadOnlyProperty<string>;
  'dots': string;
  'dotsStringProperty': TReadOnlyProperty<string>;
  'mPerSPerS': string;
  'mPerSPerSStringProperty': TReadOnlyProperty<string>;
  'densityUnitsEnglish': string;
  'densityUnitsEnglishStringProperty': TReadOnlyProperty<string>;
  'ruler': string;
  'rulerStringProperty': TReadOnlyProperty<string>;
  'mPerS': string;
  'mPerSStringProperty': TReadOnlyProperty<string>;
  'hose': string;
  'hoseStringProperty': TReadOnlyProperty<string>;
  'matchLeakage': string;
  'matchLeakageStringProperty': TReadOnlyProperty<string>;
  'atmospheres': string;
  'atmospheresStringProperty': TReadOnlyProperty<string>;
  'slowMotion': string;
  'slowMotionStringProperty': TReadOnlyProperty<string>;
  'ftPerSPerS': string;
  'ftPerSPerSStringProperty': TReadOnlyProperty<string>;
  'measuringTape': string;
  'measuringTapeStringProperty': TReadOnlyProperty<string>;
  'fill': string;
  'fillStringProperty': TReadOnlyProperty<string>;
  'psi': string;
  'psiStringProperty': TReadOnlyProperty<string>;
  'english': string;
  'englishStringProperty': TReadOnlyProperty<string>;
  'friction': string;
  'frictionStringProperty': TReadOnlyProperty<string>;
  'rateUnitsMetric': string;
  'rateUnitsMetricStringProperty': TReadOnlyProperty<string>;
  'flowRate': string;
  'flowRateStringProperty': TReadOnlyProperty<string>;
  'flowRateWithColon': string;
  'flowRateWithColonStringProperty': TReadOnlyProperty<string>;
  'kPa': string;
  'kPaStringProperty': TReadOnlyProperty<string>;
  'ft': string;
  'ftStringProperty': TReadOnlyProperty<string>;
  'gasoline': string;
  'gasolineStringProperty': TReadOnlyProperty<string>;
  'manual': string;
  'manualStringProperty': TReadOnlyProperty<string>;
  'on': string;
  'onStringProperty': TReadOnlyProperty<string>;
  'area': string;
  'areaStringProperty': TReadOnlyProperty<string>;
  'rateUnitsEnglish': string;
  'rateUnitsEnglishStringProperty': TReadOnlyProperty<string>;
  'water': string;
  'waterStringProperty': TReadOnlyProperty<string>;
  'readoutFeet': string;
  'readoutFeetStringProperty': TReadOnlyProperty<string>;
  'gravity': string;
  'gravityStringProperty': TReadOnlyProperty<string>;
  'metric': string;
  'metricStringProperty': TReadOnlyProperty<string>;
  'massLabelPattern': string;
  'massLabelPatternStringProperty': TReadOnlyProperty<string>;
  'atm': string;
  'atmStringProperty': TReadOnlyProperty<string>;
  'grid': string;
  'gridStringProperty': TReadOnlyProperty<string>;
  'normal': string;
  'normalStringProperty': TReadOnlyProperty<string>;
  'readoutMeters': string;
  'readoutMetersStringProperty': TReadOnlyProperty<string>;
  'off': string;
  'offStringProperty': TReadOnlyProperty<string>;
  'atmosphere': string;
  'atmosphereStringProperty': TReadOnlyProperty<string>;
  'areaUnitsMetric': string;
  'areaUnitsMetricStringProperty': TReadOnlyProperty<string>;
  'densityUnitsMetric': string;
  'densityUnitsMetricStringProperty': TReadOnlyProperty<string>;
  'valueWithUnitsPattern': string;
  'valueWithUnitsPatternStringProperty': TReadOnlyProperty<string>;
  'm': string;
  'mStringProperty': TReadOnlyProperty<string>;
  'fluxUnitsEnglish': string;
  'fluxUnitsEnglishStringProperty': TReadOnlyProperty<string>;
  'units': string;
  'unitsStringProperty': TReadOnlyProperty<string>;
  'flux': string;
  'fluxStringProperty': TReadOnlyProperty<string>;
  'fluxMeter': string;
  'fluxMeterStringProperty': TReadOnlyProperty<string>;
  'ftPerS': string;
  'ftPerSStringProperty': TReadOnlyProperty<string>;
  'areaUnitsEnglish': string;
  'areaUnitsEnglishStringProperty': TReadOnlyProperty<string>;
  'mars': string;
  'marsStringProperty': TReadOnlyProperty<string>;
  'jupiter': string;
  'jupiterStringProperty': TReadOnlyProperty<string>;
  'mysteryFluid': string;
  'mysteryFluidStringProperty': TReadOnlyProperty<string>;
  'mysteryPlanet': string;
  'mysteryPlanetStringProperty': TReadOnlyProperty<string>;
  'planetA': string;
  'planetAStringProperty': TReadOnlyProperty<string>;
  'planetB': string;
  'planetBStringProperty': TReadOnlyProperty<string>;
  'planetC': string;
  'planetCStringProperty': TReadOnlyProperty<string>;
  'fluidA': string;
  'fluidAStringProperty': TReadOnlyProperty<string>;
  'fluidB': string;
  'fluidBStringProperty': TReadOnlyProperty<string>;
  'fluidC': string;
  'fluidCStringProperty': TReadOnlyProperty<string>;
  'feet': string;
  'feetStringProperty': TReadOnlyProperty<string>;
  'meters': string;
  'metersStringProperty': TReadOnlyProperty<string>;
  'speed': string;
  'speedStringProperty': TReadOnlyProperty<string>;
  'flowScreenTitle': string;
  'flowScreenTitleStringProperty': TReadOnlyProperty<string>;
  'underPressureScreenTitle': string;
  'underPressureScreenTitleStringProperty': TReadOnlyProperty<string>;
};

const FluidPressureAndFlowStrings = getStringModule( 'FLUID_PRESSURE_AND_FLOW' ) as StringsType;

fluidPressureAndFlow.register( 'FluidPressureAndFlowStrings', FluidPressureAndFlowStrings );

export default FluidPressureAndFlowStrings;
